name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    name: Build and Deploy Job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check .git permissions
        run: ls -la .git

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --ci --passWithNoTests

      - name: Check dependencies
        run: |
          echo "Checking for missing dependencies..."
          npm run check:deps
          echo "Verifying build tools..."
          npm run check:build-deps

      - name: Build app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Root of the project
          api_location: "" # No API in this project
          output_location: ".next" # Next.js build folder
cd /Users/dnylhnwkyyb/lions-of-zion

# ודא שאתה על הסניף הנכון
git checkout main

# עדכן כל הקבצים במעקב
git add .

# קומיט עם הודעה מתאימה
git commit -m "Sync local with remote"

# דחוף בכוח (overwrite) ל־GitHub
git push origin main --force