name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    strategy:
      matrix:
        env: [production, staging]
        include:
          - env: production
            branch: main
          - env: staging
            branch: dev
    if: github.ref == 'refs/heads/' + matrix.branch
    name: Build and Deploy \${{ matrix.env }} Job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --ci --passWithNoTests || true

      - name: Check dependencies
        run: |
          echo "Checking for missing dependencies..."
          npm run check:deps
          echo "Verifying build tools..."
          npm run check:build-deps

      - name: Build app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: \${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: \${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ".next"
          deployment_environment: \${{ matrix.env }}
