name: Main CI and Deploy

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack and Prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: TypeScript check
        run: pnpm tsc --noEmit

      - name: Build app
        run: pnpm build

      - name: Lint
        run: pnpm lint || true

      - name: Test (optional)
        run: |
          if npm run test --if-present; then
            echo "Tests completed successfully"
          else
            echo "No tests found or tests failed (continuing anyway)"
          fi

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"            
          api_location: "api"            
          output_location: ".next"